spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: WARN
    com.urlshortener: INFO
